cp index.html ./beatsaber
cp index.html ./brawlstars
cp index.html ./callofduty
cp index.html ./csgo
cp index.html ./dota2
cp index.html ./fortnite
cp index.html ./hearthstone
cp index.html ./herosofthestorm
cp index.html ./leagueoflegends
cp index.html ./madden
cp index.html ./nba2k
cp index.html ./osu
cp index.html ./overwatch
cp index.html ./pubg
cp index.html ./rainbowsixsiege
cp index.html ./rocketleague
cp index.html ./smashmelee
cp index.html ./smashultimate
cp index.html ./starcraft2
cp index.html ./streetfighterv
cp index.html ./valorant
cp index.html ./undernightinbirth